from sc2 import Race, Difficulty
from sc2.ids.unit_typeid import UnitTypeId



DIFFICULTY_EASY = Difficulty.Easy
DIFFICULTY_MEDIUM = Difficulty.Medium
DIFFICULTY_HARD = Difficulty.Hard
DIFFICULTY_VERYHARD = Difficulty.VeryHard
DIFFICULTY_CHEAT_INSANE = Difficulty.CheatInsane

RACE_ZERG = Race.Zerg
RACE_TERRAN = Race.Terran
RACE_PROTOSS = Race.Protoss



ZERG_EXPANSION_IDS = [UnitTypeId.HATCHERY, UnitTypeId.LAIR, UnitTypeId.HIVE]
TERRAN_EXPANSION_IDS = [UnitTypeId.COMMANDCENTER, UnitTypeId.ORBITALCOMMAND, UnitTypeId.PLANETARYFORTRESS]
PROTOSS_EXPANSION_IDS = [UnitTypeId.NEXUS]

ZERG_DEFENSLESS_AIR = [UnitTypeId.OVERLORD, UnitTypeId.OVERSEER, UnitTypeId.VIPER, UnitTypeId.OVERLORDTRANSPORT, UnitTypeId.OVERLORDCOCOON]
ZERG_ANTI_AIR_STUFF = [UnitTypeId.QUEEN, UnitTypeId.HYDRALISK, UnitTypeId.MUTALISK, UnitTypeId.CORRUPTOR, UnitTypeId.INFESTOR, UnitTypeId.INFESTEDTERRAN]
PROTOSS_ANTI_AIR_STUFF = [UnitTypeId.STALKER, UnitTypeId.HIGHTEMPLAR, UnitTypeId.CARRIER, UnitTypeId.VOIDRAY, UnitTypeId.PHOENIX, UnitTypeId.ARCHON]
TERRAN_ANTI_AIR_STUFF = [UnitTypeId.MARINE, UnitTypeId.VIKING, UnitTypeId.THOR, UnitTypeId.WIDOWMINEBURROWED, UnitTypeId.CYCLONE, UnitTypeId.BATTLECRUISER, UnitTypeId.LIBERATOR]

ZERG_BUILDING_IDS = [UnitTypeId.HATCHERY, UnitTypeId.LAIR, UnitTypeId.HIVE, UnitTypeId.SPAWNINGPOOL,
                      UnitTypeId.EVOLUTIONCHAMBER, UnitTypeId.SPIRE, UnitTypeId.GREATERSPIRE, UnitTypeId.NYDUSCANAL, UnitTypeId.NYDUSNETWORK] + ZERG_EXPANSION_IDS

PROTOSS_BUILDING_IDS = [UnitTypeId.PYLON, UnitTypeId.GATEWAY, UnitTypeId.STARGATE, UnitTypeId.ROBOTICSFACILITY,
                         UnitTypeId.ROBOTICSBAY, UnitTypeId.ASSIMILATOR, UnitTypeId.TWILIGHTCOUNCIL, UnitTypeId.DARKSHRINE, UnitTypeId.FORGE, UnitTypeId.CYBERNETICSCORE, UnitTypeId.FLEETBEACON, UnitTypeId.TEMPLARARCHIVE] + PROTOSS_EXPANSION_IDS

TERRAN_BUILDING_IDS = [UnitTypeId.COMMANDCENTERFLYING,
                        UnitTypeId.ORBITALCOMMANDFLYING, UnitTypeId.BARRACKS,
                        UnitTypeId.BARRACKSFLYING, UnitTypeId.BARRACKSREACTOR, UnitTypeId.BARRACKSTECHLAB,
                        UnitTypeId.FACTORY, UnitTypeId.FACTORYFLYING, UnitTypeId.FACTORYREACTOR,
                        UnitTypeId.FACTORYTECHLAB, UnitTypeId.STARPORT, UnitTypeId.STARPORTFLYING,
                        UnitTypeId.STARPORTREACTOR, UnitTypeId.STARPORTTECHLAB, UnitTypeId.SUPPLYDEPOT,
                        UnitTypeId.ENGINEERINGBAY, UnitTypeId.ARMORY] + TERRAN_EXPANSION_IDS
